### ISSUE TITLE
Cannot Assign Hotkey cmd + space on 2.0.0-beta.16

### ISSUE THREAD

**Issue by adrianrov** [spotter-application/plugins#85]
The hotkey assignment doesn't seem to be working like it did on previous versions. It's hard to reassign and for some reason opt + space does work but it doesn't appear to be registered on the GUI

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Memory:	16 GB

System Software Overview:

  System Version:	macOS 12.0.1 (21A559)
  Kernel Version:	Darwin 21.1.0

**Comment by ziulev** [comment]
Hey @adrianrov 👋
Thank you for the issue! Please check [beta.15](https://github.com/ziulev/spotter/releases)

If the issue has been solved, please close the PR ✨

**Comment by exiva** [comment]
Seeing this on 2.0.0-beta.16. Pressing the cmd button doesn't highlight like shift, control and option do

**Comment by adrianrov** [comment]
@exiva @ziulev can confirm that the issue is still happening on 2.0.0-beta.16 opt + space works fine now though.

**Comment by exiva** [comment]
Yes, seeing it on 16. Cmd+anything doesn't work. All the other modifier keys (shift, control, opt) work fine. Cmd does not.

**Comment by Zaitam** [comment]
Could you please try this build [Spotter.zip](https://github.com/spotter-application/plugins/files/7740153/Spotter.zip)?

**Comment by adrianrov** [comment]
@Zaitam I tried your build and it seems to be working great!

**Comment by adrianrov** [comment]
@ziulev Checked version 2.0.0-beta.17 and can confirm that the issue is fixed. Thanks a lot for your hard work guys
